### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by ronanru** [skrepkaq/Battleships#11]
You are putting user input strait into SQL queries without any validation. For example here:
```python
sql.execute(F"""SELECT * FROM tokens WHERE ip = '{ip}' AND token = '{token}'
                    AND state = 1 AND time > {time.time()-86400}""")
```
(token - user-controlled variable).
I can open devtools console in my browser and paste:
```js
socket.send(
  JSON.stringify({
    type: 'authorization',
    method: 'token',
    token: "' [some malicious code]"
  })
);

```
This is major security vulnerability. It allows attackers it insert malicious code to your SQL query. 

To avoid this you should use SQL parameters as explained [here](https://docs.python.org/3/library/sqlite3.html) (the last code block).

**Comment by skrepkaq** [comment]
Because i tried, and i cant inject nothing in there

**Comment by ronanru** [comment]
You have to log out for this to work

**Comment by ronanru** [comment]
misclick, sorry

**Comment by skrepkaq** [comment]
Yea, but can u, drop table for example?

**Comment by skrepkaq** [comment]
This doesn't work in Python
