### ISSUE TITLE
Bad token generation

### ISSUE THREAD

**Issue by Trard** [skrepkaq/Battleships#2]
You are [using](https://github.com/skrepkaq/Battleships/blob/master/server/login_token.py#:~:text=token%20%2B%3D-,choice,-(abc)) choice function for generating tokens.

[Choice function](https://docs.python.org/3/library/random.html#random.choice) is part of the [random lib](https://docs.python.org/3/library/random.html). This lib generates pseudo-random numbers.
This is not safe and looks weird in the code.

Use the [secrets library](https://docs.python.org/3/library/secrets.html). I also recommend taking a closer look at [secrets.token_hex](https://docs.python.org/3/library/secrets.html#secrets.token_hex).

**Comment by skrepkaq** [comment]
Thank you!
